### ISSUE TITLE
bl.ocks.org is down

### ISSUE THREAD

**Issue by pygy** [chart-code/blocks#26]
It has been for months now

You may want to update the home page to reflect that...

Also, given that the original is down, https://blocks.roadtolarissa.com being a drop-in replacement as a gist viewer increases the likelihood you could get viral traffic at some point.

I see that you're hosted by @digitalocean, you may want to contact them and negotiate a sponsoring arrangement (infinite bandwith vs their brand on the home page often works for this kind of situation, not sure if they'd agree to go for it).

**Comment by 1wheel** [comment]
Thanks — I've updated the bl.ocks.org link.

I'm not too worried about bandwidth yet; not anywhere close to digital ocean's default limit and it isn't the end of the world if the site goes down for a bit while fixing it.

**Comment by pygy** [comment]
Great, we can close this as far as I'm concerned
